channels:
  - conda-forge
dependencies:
  # Core Python
  - python=3.11
  
  # Essential data science packages
  - numpy=1.26.4
  - pandas=2.2.1
  - scipy=1.12.0
  
  # Plotting
  - matplotlib=3.8.3
  - seaborn=0.13.2
  - plotly=5.17.0
  
  # Time series analysis
  - statsmodels=0.14.1
  - pmdarima=2.0.4
  - scikit-learn=1.4.1
  
  # Data sources
  - yfinance=0.2.40
  - fredapi=0.5.2
  
  # Jupyter environment
  - jupyter=1.0.0
  - notebook=7.1.2
  - jupyterlab=4.1.5
  - ipykernel=6.29.3
  
  # PDF export capabilities
  - pandoc=3.6.4
  - nbconvert=7.16.6
  
  # Utilities
  - requests=2.31.0
  - beautifulsoup4=4.12.3
  - lxml=5.3.0
  
  # Additional packages via pip
  - pip=24.0
  - pip:
      - pandas-datareader==0.10.0
      - quandl==3.7.0